import Foundation

/// Pure presentation rules for feedback generated by a completed train journey.
///
/// These calculations deliberately do not mutate the economy. The displayed fare revenue is an
/// allocation of the line's existing daily projection, while horn timing is derived solely from
/// stable train identity and a caller-owned station-arrival ordinal.
nonisolated enum TrainJourneyPresentation {
    /// A train sounds once in every eight station arrivals, after a UUID-derived initial delay.
    static let hornIntervalArrivals: UInt64 = 8

    /// The earliest any train can sound after its arrival ordinal starts at one.
    static let earliestHornArrival: UInt64 = 4

    /// Allocates projected daily fare revenue across all scheduled one-way terminal arrivals.
    ///
    /// Invalid or non-operating schedules return zero. If the scheduled-trip multiplication
    /// overflows, its true value is greater than `Int64.max` and therefore also greater than any
    /// valid positive `dailyRevenuePence`; the whole-pence result is consequently zero.
    static func fareRevenuePencePerTerminalArrival(
        dailyRevenuePence: Int64,
        departuresPerHour: Int,
        serviceHoursPerDay: Int64,
        directionCount: Int64
    ) -> Int64 {
        guard dailyRevenuePence > 0,
              departuresPerHour > 0,
              serviceHoursPerDay > 0,
              directionCount > 0 else {
            return 0
        }

        let departures = Int64(clamping: departuresPerHour)
        let departuresAndHours = departures.multipliedReportingOverflow(
            by: serviceHoursPerDay
        )
        guard !departuresAndHours.overflow else { return 0 }

        let scheduledArrivals = departuresAndHours.partialValue
            .multipliedReportingOverflow(by: directionCount)
        guard !scheduledArrivals.overflow, scheduledArrivals.partialValue > 0 else {
            return 0
        }

        return dailyRevenuePence / scheduledArrivals.partialValue
    }

    /// Allocates projected revenue across every advertised station arrival. Endpoints are served
    /// by the full timetable, while intermediate calls may be served only by local trains.
    static func fareRevenuePencePerStationArrival(
        dailyRevenuePence: Int64,
        endpointDeparturesPerHour: Int,
        intermediateDeparturesPerHour: Int,
        intermediateStationCount: Int,
        serviceHoursPerDay: Int64,
        directionCount: Int64
    ) -> Int64 {
        guard dailyRevenuePence > 0,
              endpointDeparturesPerHour > 0,
              intermediateDeparturesPerHour >= 0,
              intermediateStationCount >= 0,
              serviceHoursPerDay > 0,
              directionCount > 0 else { return 0 }

        let intermediateCalls = Int64(clamping: intermediateDeparturesPerHour)
            .multipliedReportingOverflow(by: Int64(clamping: intermediateStationCount))
        guard !intermediateCalls.overflow else { return 0 }
        let callsPerDirectionPerHour = Int64(clamping: endpointDeparturesPerHour)
            .addingReportingOverflow(intermediateCalls.partialValue)
        guard !callsPerDirectionPerHour.overflow,
              callsPerDirectionPerHour.partialValue > 0 else { return 0 }
        let callsAndHours = callsPerDirectionPerHour.partialValue
            .multipliedReportingOverflow(by: serviceHoursPerDay)
        guard !callsAndHours.overflow else { return 0 }
        let scheduledArrivals = callsAndHours.partialValue
            .multipliedReportingOverflow(by: directionCount)
        guard !scheduledArrivals.overflow, scheduledArrivals.partialValue > 0 else {
            return 0
        }
        return dailyRevenuePence / scheduledArrivals.partialValue
    }

    /// Convenience overload using the game's passenger-facing service frequency.
    static func fareRevenuePencePerTerminalArrival(
        dailyRevenuePence: Int64,
        frequency: ServiceFrequency,
        serviceHoursPerDay: Int64,
        directionCount: Int64
    ) -> Int64 {
        fareRevenuePencePerTerminalArrival(
            dailyRevenuePence: dailyRevenuePence,
            departuresPerHour: frequency.departuresPerHour,
            serviceHoursPerDay: serviceHoursPerDay,
            directionCount: directionCount
        )
    }

    /// Returns a sparse, deterministic horn decision for a one-based station-arrival ordinal.
    ///
    /// Each train receives a stable first horn between arrivals four and eleven, then sounds every
    /// eight arrivals. This both staggers a fleet and guarantees a bounded cadence without random
    /// state, timers or Swift's intentionally process-randomized `Hasher`.
    static func shouldSoundHorn(trainID: UUID, arrivalOrdinal: UInt64) -> Bool {
        guard arrivalOrdinal > 0 else { return false }

        let firstHorn = earliestHornArrival + stableHornPhase(for: trainID)
        guard arrivalOrdinal >= firstHorn else { return false }
        return (arrivalOrdinal - firstHorn).isMultiple(of: hornIntervalArrivals)
    }

    private static func stableHornPhase(for trainID: UUID) -> UInt64 {
        // FNV-1a over UUID text is small, portable and stable across launches and devices.
        let offsetBasis: UInt64 = 14_695_981_039_346_656_037
        let prime: UInt64 = 1_099_511_628_211
        let hash = trainID.uuidString.utf8.reduce(offsetBasis) { partialHash, byte in
            (partialHash ^ UInt64(byte)) &* prime
        }
        return hash % hornIntervalArrivals
    }
}
